apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tfd-blog-ingress
  namespace: prod
  labels:
    app: tfd-blog
    environment: prod
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: tfdevs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tfd-blog-service
                port:
                  number: 80
